
name: "Documentation"

on:
    pull_request:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"
        paths:
            - 'doc/**'
            - '.github/workflows/docs.yaml'
    push:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"
            - "*_actions"
        paths:
            - 'doc/**'

permissions:
  contents: read

jobs:
    docs:
        name: "Generate docs Pimcore Docs Generator"
        runs-on: "ubuntu-20.04"
        steps:
            - name: "Checkout code"
              uses: "actions/checkout@v3"

            - name: "Checkout Docs Generator"
              uses: "actions/checkout@v3"
              with:
                  repository: "pimcore/docs-generator"
                  ref: "prepare-repos-test"
                  path: "./docs-generator"
                  token: ${{ secrets.DOCS_GENERATOR_ACCESS_TOKEN }}

            - uses: actions/setup-node@v3
              with:
                  node-version: 19
                  cache: 'npm'

            - name: Prepare Docs
              working-directory: "./docs-generator"
              run: |
                  mkdir docs
                  # copy docs to working directory
                  cp -r ../doc ./docs/
                  
                  # copy index page
                  cp bin/resources/00_index.md  ./docs/
                  
                  # use special docusaurus config (to exclude search plugin) and check for broken links
                  mv docusaurus.config.js.repos-tests docusaurus.config.js
                  
            - name: Build Docs
              working-directory: "./docs-generator"
              run: |
                  npm install
                  npm build
                  
